module.exports.MESSAGES = {
    WELCOME: 'Welcome To Skype Alerting Bot! Please Send Username:Password:Group (Groups Are zabbix, grafana, all)',
    LOGGEDOUT: 'You Logged Out!',
    ERROR: 'Error! Please Try Again!',
    DELETEACCOUNT: 'Your Account Has Been Deleted!',
    ADMINDELETEACCOUNT: 'The Requested Account Has Been Deleted!',
    CREATEUSER: 'User Created!',
    INTERNAL: 'Internal Error!',
    ISADMIN: 'isAdmin should be boolean',
    EMPTYUSERORPASS: 'username or password is empty',
    USEREXISTS: 'user already exists',
    CHANGEPASS: 'Password Changed!',
    GROUPCHANGE: 'Group Changed!',
    WRONGACC: 'Wrong User/Pass',
    LOGGEDINADMIN: 'You Are Now Logged In As An Admin!',
    LOGGEDINUSER: 'You Are Now Logged In!',
    HELPINTRO: 'If you want list of commands enter: help',
    ONLYLOGIN: 'I Can Only Get User/pass',
    HELP: `logout\ndelete account\nchange password:yournewpass\ngroup:all  ||  zabbix  ||  grafana`,
    ADMINHELP: `logout\ndelete account\nchange password:yournewpass\ngroup:all  ||  zabbix  ||  grafana\nadmin:create account:username:password:isAdmin (for e.g. admin:create account:test:testpass:true)\nadmin:delete account:username\n admin:show accounts`,
};